#!/bin/bash

# Config
cp -r /home/$USER/.config/i3 .
cp -r /home/$USER/.config/alacritty .
cp -r /home/$USER/.config/picom .
cp -r /home/$USER/.config/polybar .
cp -r /home/$USER/.config/rofi .

# Custom Bin
cp -r /home/$USER/bin .

# Bash
cp /home/$USER/.bashrc .

# Vim
cp /home/$USER/.vimrc .

# Xinitrc
cp /home/$USER/.xinitrc .
