#!/bin/bash

# Config
cp -r $HOME/.config/i3 .
cp -r $HOME/.config/alacritty .
cp -r $HOME/.config/picom .
cp -r $HOME/.config/polybar .
cp -r $HOME/.config/rofi .

# Custom Bin
cp -r $HOME/bin .

# Bash
cp $HOME/.bashrc .

# Vim
cp $HOME/.vimrc .

# Xinitrc
cp $HOME/.xinitrc .
